version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo-dev
    restart: always

    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis
    container_name: cache
    networks:
      - app-network
    volumes:
      - ./redis-data:/data
    restart: always
    ports:
      - "6379:6379"
  api-server:
    build:
      context: ./api
    container_name: api-server
    image: api-server
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=1
    depends_on:
      - mongo
      - redis
    volumes:
      - ./logs:/logs
      - "./api:/usr/src/services/api"
      - "./api/node_modules:/usr/src/services/api/node_modules"
    networks:
      - app-network
    ports:
      - "4000:4000"

networks:
  app-network:
    driver: bridge
