# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: npm install, build and test
        env:
          TEST_MONGO_URI: ${{secrets.TEST_MONGO_URI}}
          BASE_URL: ${{secrets.BASE_URL}}
          APP_SECRET: ${{secrets.APP_SECRET}}
          REFRESH_SECRET: ${{secrets.REFRESH_SECRET}}
          REDIS_URL: ${{secrets.REDIS_URL}}
          REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
        run: |
          run: npm ci
          npm install
          npm run quick-build
          npm test
